### ISSUE TITLE
Add price for external website for current value of the card

### ISSUE THREAD

**Issue by eembling** [Japnix/Marcie#14]
Add a current value price for the card. This will help with trades and search ability of the card

Example:
Cloud of Darkness - Water 5 - (5-126L)
Forward Wraith MOBIUS · III
When Cloud of Darkness enters the field, choose 1 Forward opponent controls. It loses 2000 power for each Forward you control until the end of the turn.
When Cloud of Darkness attacks, choose 1 Forward opponent controls. It loses 1000 power for each Forward you control until the end of the turn.
8000
**Price: $5.12 - link**
ID: 4ba1ddbe7b•Today at 10:18 AM

**Comment by btawa** [comment]
Doing this without an API is pretty tough.  TCG Players API isn't open.  And I don't know where I would get this information other than scraping html.  Likely won't get implemented.

**Comment by btawa** [comment]
I got access to TCGPlayers API so this may be possible.  Will look into.

**Comment by btawa** [comment]
Never going to get to this
