### ISSUE TITLE
?card embed for Opus 1 cards uses Opus 11 card with corresponding card code's image.

### ISSUE THREAD

**Issue by eureka-bots** [Japnix/Marcie#18]
Invoking ?name and selecting an Opus 1 card will result in an embed that has the thumbnail of the Opus 11 card with the corresponding card code. Having taken no look I'm guessing there's some parsing issue.

**Steps to Reproduce**  
1. Invoke ?name and select any Opus 1 card  
ex. `?name Auron` , (1 for 1-001H Auron)  
This will result in an embed with the thumbnail of 11-001C Ifrit.

**Expected Behavior**
The embed has the thumbnail of the card selected.

**Comment by btawa** [comment]
Thanks for reporting.  I'll see about fixing this soon.

**Comment by btawa** [comment]
Should be fixed now.

**Comment by btawa** [comment]
Closing issue
